version: '3.0'

services:
  auth:
    build: ./auth
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - redis
    links: ["redis"] 
    networks:
      - web
  dl:
    build: ./dl
    restart: always
    ports:
      - "8082:8080"
    networks:
      - web

  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge
